version: '3'

services:
  postgres:
    build:
      context: .
      dockerfile: ./compose/local/postgres/Dockerfile
    image: sandbox_local_postgres
    container_name: sandbox_local_postgres
    volumes:
      - ./db:/var/lib/postgresql/data
    env_file:
      - ./.envs/.local/.postgres

  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: sandbox_local_django
    container_name: sandbox_local_django
    stdin_open: true
    depends_on:
      - postgres
    volumes:
      - .:/app
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
