# Generated by Django 3.2.4 on 2021-06-21 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InputImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='input_image')),
            ],
            options={
                'db_table': 'input_image',
            },
        ),
    ]
